version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: gravity
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
