default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: 5432 #<%= ENV.fetch('DATABASE_PORT', 5432) %>
  username: 'gravity' #<%= ENV.fetch('DATABASE_USER', 'gravity') %>
  password: 'test' #<%= ENV.fetch('DATABASE_PASS', 'test') %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
  url: <%= ENV.fetch('DATABASE_URL', '/') %>
