default: &default
  adapter: postgresql 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  username: <%= ENV.fetch('DATABASE_USER', 'gravity') %>
  password: <%= ENV.fetch('DATABASE_PASS', 'test') %>


test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
  url: <%= ENV.fetch('DATABASE_URL', '/') %>
